// sql语句
var sqlMap = {
    // 用户
    user: {
        addManager: 'INSERT INTO manager(id, username, password, idnumber) VALUES (0, ?, ?, ?)',
        addStaff: 'INSERT INTO staff(id, username, password ,idnumber) VALUES (0, ?, ?, ?)',
        check: 'SELECT * FROM manager WHERE username = ? AND password = ?',
        exist: 'SELECT * FROM manager WHERE username = ?',
        existStaff: 'SELECT * FROM staff WHERE username = ?',
        checkStaff: 'SELECT * FROM staff WHERE username = ? AND password = ?',
        staffInfo: 'SELECT * FROM staffInfo',
        personalDetail: 'SELECT * FROM staffInfo WHERE idnumber = ?',
        updateStaff: 'UPDATE staffInfo SET name=?,sex=?,birth=?,education=?,profession=?,address=?,duties=?,salary=?,checkin=?,depart=?,status=?,phone=? WHERE idnumber = ?',
    	hrInfo: 'SELECT * FROM hrInfo',
    	updateHrInfo: 'UPDATE hrInfo SET jobaddress=?,education=?,workyears=?,jobdescription=?,jobrequirements=?,releasetime=? WHERE id=?',
		addHireInfo: 'INSERT INTO hrInfo(id,jobname,jobkind,jobtype,jobaddress,jobquantity,releasetime,education,workyears,jobdescription,jobrequirements) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
    	deliverResume: 'INSERT INTO resume( id,name,jobname,sex,phone,education,profession,email,skills,project,releasetime) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )',
    	getResume: 'SELECT * FROM resume',
        searchName: 'SELECT * FROM staffInfo WHERE name = ?',
        searchDuties: 'SELECT * FROM staffInfo WHERE duties = ?',
        searchDepart: 'SELECT * FROM staffInfo WHERE depart = ?',
        searchInfo: 'SELECT * FROM staffInfo WHERE name = ? OR duties = ? OR depart = ?',
        deleteHireInfo: 'DELETE FROM hrInfo WHERE id = ?',
        deleteStaff: 'DELETE FROM staffInfo WHERE id = ?',
        addNewStaff: 'INSERT INTO staffInfo(id,name,sex,birth,education,profession,address,duties,salary,checkin,depart,status,phone) VALUES( ?,?,?,?,?,?,?,?,?,?,?,?,? )',
        userInfo: 'SELECT * FROM staff',
        changePs: 'UPDATE manager SET password=? WHERE username=?',
        changeStaffPs: 'UPDATE staff SET password=? WHERE username=?',
        addInterview: 'INSERT INTO interview(id,name,email,phone,interviewer,date,time,status,pass) VALUES(?,?,?,?,?,?,?,?,?)',
        getInterview: 'SELECT * FROM interview',
        passInterview: 'INSERT INTO talent(name,phone,email,id) VALUES(?,?,?,?)',
        updateInterview: 'UPDATE interview SET status=?,pass=? WHERE id = ?',
        getTalent: 'SELECT * FROM talent',
        trainInfo: 'SELECT * FROM trainInfo',
        addTrainInfo: 'INSERT INTO trainInfo(topic,staff,date,time,place,content,id) VALUES (?,?,?,?,?,?,0)',
        personalTrain: 'INSERT INTO personalTrain(topic,name,sex,depart,duties,date,content,experience,idnumber,id) VALUES (?,?,?,?,?,?,?,?,?,0)',
        getPersonalT: 'SELECT * FROM personalTrain WHERE idnumber= ?',
        getAllTrainInfo: 'SELECT * FROM personalTrain',
        checkinAM: 'INSERT INTO checkinAM(id,idnumber,info,time,date) VALUES (0,?,?,?,?)',
        checkinPM: 'INSERT INTO checkinPM(id,idnumber,info,time,date) VALUES (0,?,?,?,?)',
        qingjia: 'INSERT INTO note(id,idnumber,name,leavedate,rebackdate,reason,status,releasetime) VALUES (0,?,?,?,?,?,?,?)',
        mynote: 'SELECT * FROM note WHERE idnumber = ?',
        allnote: 'SELECT * FROM note',
        passnote: 'UPDATE note SET status=? WHERE id=?',
        notpassnote: 'UPDATE note SET status=?,backreason=? WHERE id=?',
        mycheckAM: "SELECT * FROM checkinAM WHERE idnumber = ? AND (info ='旷工' OR info ='上班迟到')",
        mycheckPM: "SELECT * FROM checkinPM WHERE idnumber = ? AND (info ='早退' OR info ='加班')",
        allcheckAM: "SELECT * FROM checkinAM WHERE info ='旷工' OR info ='上班迟到'",
        allcheckPM: "SELECT * FROM checkinPM WHERE info ='早退' OR info ='加班'",
        allwork: "SELECT * FROM typeOfWork",
        changeSM: "UPDATE typeOfWork SET workname=?,depart=?,salary=? WHERE id=?",
        addNewWork: "INSERT INTO typeOfWork(id,workname,depart,salary) VALUES(0,?,?,?)"
    }
}

module.exports = sqlMap;